package net.syllyaddons.audit;

public enum AuditFindingType {
    NEGATIVE_NET_PRODUCTION,
    UNSUSTAINABLE_TOWER_UPKEEP,
    PRODUCTION_NOT_REACHING_HQ,
    SINGLE_ROUTE_OR_CHOKEPOINT,
    SIMULTANEOUS_SURPLUS_AND_DEFICIT,
    STORAGE_OR_TREASURY_RISK,
    LONG_OR_EXPENSIVE_ROUTE,
    DOMINATED_ECONOMIC_UPGRADE,
    LOW_VALUE_UPGRADE,
    POTENTIALLY_SAFE_DOWNGRADE
}
