org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=syllyaddons
mod_name=Sylly Addons
mod_version=0.1.0-dev
maven_group=net.syllyaddons
archives_base_name=syllyaddons

java_version=21
minecraft_version=1.21.11
fabric_loader_version=0.19.3
fabric_api_version=0.141.5+1.21.11
modmenu_version=17.0.1-beta.1
architectury_loom_version=1.13-SNAPSHOT
parchment_version=1.21.11:2025.12.20
junit_version=5.13.4
junit_platform_version=1.13.4

supported_wynntils_version=4.2.8
supported_wynntils_sha256=00369b5950a9522b8feed3122a4ec15dd581347c8fa868670650b76bac1380f6
