org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_version=0.1.0-dev
maven_group=net.syllyaddons
archives_base_name=sylly-dev-recorder

java_version=21
minecraft_version=1.21.11
fabric_loader_version=0.19.3
fabric_api_version=0.141.5+1.21.11
architectury_loom_version=1.13-SNAPSHOT
parchment_version=1.21.11:2025.12.20

supported_wynntils_version=4.2.9
supported_wynntils_sha256=faf32c32c5ce3af3b7236a19c5b8b8c6fb44695bf4340a9083bd2eae744858ef
